version: 2
jobs:
  build-front:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo build-front step

  build-back:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo build-back step

  test-front:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo test-front step
  
  test-back:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo test-back step

  integration:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo integration step

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo deploy step

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-front
      - built-back
      - test-front:
          requires:
            - build-front
      - test-back:
          requires:
            - build-back
      - integration:
          requires:
            - test-front
            - test-back
      - deploy
          requires:
            - integration
          filters:
            branches:
              only:
                - master
      
